import { useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, Gavel, Loader2, Plus, RefreshCw, ShieldQuestion, X } from "lucide-react";
import { api, useStore } from "@/state/store";
import { cn } from "@/lib/cn";

type Status = "exploring" | "decided" | "revisit" | "archived";
type Decision = { id: string; botId: string | null; question: string; options: string[]; assumptions: string[]; counterCase: string; choice: string; rationale: string; confidence: number | null; reviewAt: number | null; status: Status; challengedAt: number | null; decidedAt: number | null; createdAt: number; updatedAt: number; reviewDue: boolean };
const splitLines = (value: string) => [...new Set(value.split("\n").map((item) => item.replace(/^[-*]\s*/, "").trim()).filter(Boolean))];
const empty = { question: "", options: "", assumptions: "", counterCase: "", choice: "", rationale: "", confidence: "", reviewDate: "", status: "exploring" as Status };

export function DecisionJournalDialog() {
  const { state } = useStore(); const [open, setOpen] = useState(false); const [decisions, setDecisions] = useState<Decision[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const selected = decisions.find((item) => item.id === selectedId) ?? null;
  const challengeBot = useMemo(() => state.bots.find((bot) => bot.id === state.selectedId && !bot.hidden) ?? state.bots.find((bot) => !bot.hidden) ?? null, [state.bots, state.selectedId]);
  const load = async (keepId?: string | null) => { const result = await api("/api/decisions", { cache: "no-store" }) as { decisions: Decision[] }; setDecisions(result.decisions); const nextId = keepId && result.decisions.some((item) => item.id === keepId) ? keepId : result.decisions[0]?.id ?? null; setSelectedId(nextId); if (!nextId) setForm(empty); };
  useEffect(() => { if (!open) return; setBusy("load"); setError(""); void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load decisions")).finally(() => setBusy("")); }, [open]);
  useEffect(() => { if (!selected) return; setForm({ question: selected.question, options: selected.options.join("\n"), assumptions: selected.assumptions.join("\n"), counterCase: selected.counterCase, choice: selected.choice, rationale: selected.rationale, confidence: selected.confidence === null ? "" : String(selected.confidence), reviewDate: selected.reviewAt ? new Date(selected.reviewAt).toISOString().slice(0, 10) : "", status: selected.status }); }, [selected]);
  const payload = (status = form.status) => ({ question: form.question, options: splitLines(form.options), assumptions: splitLines(form.assumptions), counterCase: form.counterCase, choice: form.choice, rationale: form.rationale, confidence: form.confidence === "" ? null : Number(form.confidence), reviewAt: form.reviewDate ? new Date(`${form.reviewDate}T23:59:00`).getTime() : null, status });
  const save = async (status: Status) => { setBusy("save"); setError(""); try { const result = await api(selectedId ? `/api/decisions/${selectedId}` : "/api/decisions", { method: selectedId ? "PATCH" : "POST", body: JSON.stringify(payload(status)) }) as { decision: Decision }; await load(result.decision.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save the decision"); } finally { setBusy(""); } };
  const challenge = async () => { if (!selectedId || !challengeBot) return; setBusy("challenge"); setError(""); try { await api(`/api/decisions/${selectedId}`, { method: "PATCH", body: JSON.stringify(payload("exploring")) }); const result = await api(`/api/decisions/${selectedId}/challenge`, { method: "POST", body: JSON.stringify({ botId: challengeBot.id }) }) as { counterCase: string }; setForm((current) => ({ ...current, counterCase: result.counterCase, status: "exploring" })); await load(selectedId); } catch (reason) { setError(reason instanceof Error ? reason.message : "The challenge did not complete"); } finally { setBusy(""); } };
  const archive = async () => { if (!selectedId) return; setBusy("archive"); try { await api(`/api/decisions/${selectedId}`, { method: "PATCH", body: JSON.stringify(payload("archived")) }); await load(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not archive the decision"); } finally { setBusy(""); } };
  const newDecision = () => { setSelectedId(null); setForm(empty); setError(""); };
  const canSave = form.question.trim() && splitLines(form.options).length >= 2; const canDecide = canSave && form.choice.trim() && form.rationale.trim();

  return <>
    <button onClick={() => setOpen(true)} className="flex min-h-10 items-center gap-2 rounded-xl border border-hairline/40 bg-card px-3.5 text-[12.5px] font-medium text-ink hover:bg-inset"><Gavel size={15} className="text-accent" />Decisions</button>
    {open && <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/55 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="decision-journal-title"><div className="flex max-h-[96dvh] w-full max-w-6xl flex-col overflow-hidden rounded-t-2xl border border-hairline/40 bg-card shadow-2xl sm:max-h-[90dvh] sm:rounded-2xl">
      <header className="flex items-start justify-between gap-4 border-b border-hairline/30 px-4 py-4 sm:px-5"><div><div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-[.14em] text-accent"><Gavel size={14} />Decision journal</div><h2 id="decision-journal-title" className="mt-1 text-[20px] font-semibold text-ink">Decide with a record</h2><p className="mt-1 text-[12px] text-ink-secondary">Frame options, challenge the leading view, then record why.</p></div><button aria-label="Close decision journal" onClick={() => setOpen(false)} className="flex size-10 shrink-0 items-center justify-center rounded-xl text-ink-secondary hover:bg-inset"><X size={18} /></button></header>
      <div className="grid min-h-0 flex-1 overflow-hidden md:grid-cols-[260px_minmax(0,1fr)]">
        <aside className="max-h-48 overflow-y-auto border-b border-hairline/30 p-3 md:max-h-none md:border-b-0 md:border-r"><button onClick={newDecision} className="flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-accent px-3 text-[12.5px] font-medium text-white"><Plus size={14} />New decision</button><div className="mt-2 space-y-1">{busy === "load" ? <div className="flex justify-center py-8"><Loader2 size={18} className="animate-spin text-accent" /></div> : decisions.length === 0 ? <div className="px-2 py-6 text-center text-[12px] text-ink-secondary">No decisions recorded yet.</div> : decisions.map((item) => <button key={item.id} onClick={() => setSelectedId(item.id)} className={cn("w-full rounded-xl px-3 py-2.5 text-left", selectedId === item.id ? "bg-raised" : "hover:bg-inset")}><div className="line-clamp-2 text-[12.5px] font-medium text-ink">{item.question}</div><div className="mt-1 flex items-center gap-2 text-[10.5px] text-ink-secondary"><span className={cn("size-1.5 rounded-full", item.status === "decided" ? "bg-success" : item.status === "revisit" || item.reviewDue ? "bg-warning" : "bg-accent")} />{item.reviewDue ? "Review due" : item.status}</div></button>)}</div></aside>
        <main className="min-h-0 overflow-y-auto p-4 sm:p-5">{error && <div role="alert" className="mb-4 rounded-xl bg-danger/10 px-3 py-2.5 text-[12.5px] text-danger">{error}</div>}<div className="space-y-4">
          <label className="block"><span className="mb-1.5 block text-[12px] font-medium text-ink">Decision question</span><input value={form.question} onChange={(event) => setForm((current) => ({ ...current, question: event.target.value }))} maxLength={500} placeholder="What are we deciding?" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none" /></label>
          <div className="grid gap-4 lg:grid-cols-2"><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Real options</span><textarea value={form.options} onChange={(event) => setForm((current) => ({ ...current, options: event.target.value }))} placeholder={"One option per line\nInclude the status quo"} className="min-h-32 w-full resize-y rounded-xl border border-hairline/40 bg-inset p-3 text-[13px] leading-relaxed text-ink focus:border-accent focus:outline-none" /></label><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Assumptions</span><textarea value={form.assumptions} onChange={(event) => setForm((current) => ({ ...current, assumptions: event.target.value }))} placeholder="What must be true?" className="min-h-32 w-full resize-y rounded-xl border border-hairline/40 bg-inset p-3 text-[13px] leading-relaxed text-ink focus:border-accent focus:outline-none" /></label></div>
          <section className="rounded-xl border border-hairline/35 bg-inset p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-[12.5px] font-semibold text-ink">Strongest opposing case</h3><p className="mt-0.5 text-[11px] text-ink-secondary">Have {challengeBot?.name ?? "a bot"} red-team the leading view, or write it yourself.</p></div><button disabled={!selectedId || !canSave || !challengeBot || busy === "challenge"} onClick={() => void challenge()} className="flex min-h-10 items-center gap-2 rounded-lg bg-card px-3 text-[12px] font-medium text-accent disabled:opacity-40">{busy === "challenge" ? <Loader2 size={14} className="animate-spin" /> : <ShieldQuestion size={14} />}Challenge</button></div><textarea value={form.counterCase} onChange={(event) => setForm((current) => ({ ...current, counterCase: event.target.value }))} placeholder="The strongest reason the leading choice may be wrong…" className="mt-3 min-h-40 w-full resize-y rounded-xl border border-hairline/35 bg-card p-3 text-[12.5px] leading-relaxed text-ink focus:border-accent focus:outline-none" /></section>
          <div className="grid gap-4 lg:grid-cols-2"><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Choice</span><input value={form.choice} onChange={(event) => setForm((current) => ({ ...current, choice: event.target.value }))} placeholder="What did you choose?" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none" /></label><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Confidence</span><input type="number" min="0" max="100" value={form.confidence} onChange={(event) => setForm((current) => ({ ...current, confidence: event.target.value }))} placeholder="0–100" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none" /></label></div>
          <label className="block"><span className="mb-1.5 block text-[12px] font-medium text-ink">Rationale</span><textarea value={form.rationale} onChange={(event) => setForm((current) => ({ ...current, rationale: event.target.value }))} placeholder="Why this choice, given the counter-case?" className="min-h-32 w-full resize-y rounded-xl border border-hairline/40 bg-inset p-3 text-[13px] leading-relaxed text-ink focus:border-accent focus:outline-none" /></label>
          <label className="block max-w-xs"><span className="mb-1.5 block text-[12px] font-medium text-ink">Review date</span><input type="date" value={form.reviewDate} onChange={(event) => setForm((current) => ({ ...current, reviewDate: event.target.value }))} className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[12.5px] text-ink focus:border-accent focus:outline-none" /></label>
        </div></main>
      </div>
      <footer className="flex flex-col-reverse gap-2 border-t border-hairline/30 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div>{selectedId && <button disabled={busy === "archive"} onClick={() => void archive()} className="flex min-h-10 items-center gap-2 rounded-xl px-3 text-[12px] text-ink-secondary hover:bg-danger/10 hover:text-danger"><Archive size={14} />Archive</button>}</div><div className="flex flex-col-reverse gap-2 sm:flex-row"><button disabled={!canSave || Boolean(busy)} onClick={() => void save("exploring")} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-hairline/40 px-4 text-[12.5px] font-medium text-ink disabled:opacity-40">{busy === "save" ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}Save exploration</button><button disabled={!canDecide || Boolean(busy)} onClick={() => void save(form.reviewDate ? "revisit" : "decided")} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-5 text-[12.5px] font-medium text-white disabled:opacity-40"><CheckCircle2 size={15} />Record decision</button></div></footer>
    </div></div>}
  </>;
}
