import { api, useStore, type Bot } from "@/state/store";
import { ArrowRight, Bot as BotIcon, CheckCircle2, Clock3, Loader2, RotateCcw, Send, X, XCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

type Delegation = { id: string; sourceBotId: string | null; sourceBotName: string; targetBotId: string; targetBotName: string; task: string; context: string; expectedOutput: string; status: "queued" | "running" | "completed" | "failed" | "cancelled"; result: string | null; error: string | null; targetThreadId: string | null; createdAt: number; updatedAt: number };

function elapsed(at: number) { const minutes = Math.max(0, Math.round((Date.now() - at) / 60_000)); return minutes < 1 ? "Just now" : minutes < 60 ? `${minutes}m ago` : new Date(at).toLocaleDateString([], { month: "short", day: "numeric" }); }

export function DelegationDialog({ onChanged }: { onChanged?: () => void }) {
  const { dispatch } = useStore();
  const [open, setOpen] = useState(false); const [bots, setBots] = useState<Bot[]>([]); const [items, setItems] = useState<Delegation[]>([]);
  const [sourceBotId, setSourceBotId] = useState(""); const [targetBotId, setTargetBotId] = useState(""); const [task, setTask] = useState(""); const [context, setContext] = useState(""); const [expectedOutput, setExpectedOutput] = useState("");
  const [busy, setBusy] = useState(false); const [retrying, setRetrying] = useState(""); const [error, setError] = useState("");
  const availableTargets = useMemo(() => bots.filter((bot) => !bot.hidden && bot.id !== sourceBotId), [bots, sourceBotId]);
  const load = useCallback(async () => {
    const [roster, history] = await Promise.all([api("/api/bots") as Promise<{ bots: Bot[] }>, api("/api/delegations") as Promise<{ delegations: Delegation[] }>]);
    setBots(roster.bots.filter((bot) => !bot.hidden)); setItems(history.delegations); setTargetBotId((value) => value || roster.bots.find((bot) => !bot.hidden)?.id || "");
  }, []);
  useEffect(() => { if (open) void load().catch((cause) => setError(cause instanceof Error ? cause.message : String(cause))); }, [load, open]);
  useEffect(() => { if (!open) return; const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) setOpen(false); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [busy, open]);

  const delegate = async () => {
    if (!targetBotId || !task.trim()) return; setBusy(true); setError("");
    try {
      const response = await api("/api/delegations", { method: "POST", body: JSON.stringify({ sourceBotId: sourceBotId || null, targetBotId, task, context, expectedOutput }) }) as { delegation: Delegation };
      setItems((current) => [response.delegation, ...current.filter((item) => item.id !== response.delegation.id)]); setTask(""); setContext(""); setExpectedOutput(""); onChanged?.();
    } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); }
  };
  const retry = async (item: Delegation) => { setRetrying(item.id); setError(""); try { const response = await api(`/api/delegations/${item.id}/retry`, { method: "POST" }) as { delegation: Delegation }; setItems((current) => current.map((entry) => entry.id === item.id ? response.delegation : entry)); onChanged?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setRetrying(""); } };
  const approve = async (item: Delegation) => { setRetrying(item.id); setError(""); try { const response = await api(`/api/delegations/${item.id}/approve`, { method: "POST" }) as { delegation: Delegation }; setItems((current) => current.map((entry) => entry.id === item.id ? response.delegation : entry)); onChanged?.(); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setRetrying(""); } };
  const openResult = (item: Delegation) => { if (!item.targetThreadId) return; setOpen(false); dispatch({ type: "select", id: item.targetBotId }); dispatch({ type: "switchTask", botId: item.targetBotId, threadId: item.targetThreadId }); };

  return <><button onClick={() => setOpen(true)} className="flex min-h-10 items-center gap-2 rounded-xl border border-hairline/40 bg-card px-3 text-[12.5px] text-ink-secondary hover:text-ink"><Send size={14} />Delegate</button>{open && createPortal(<div className="fixed inset-0 z-[70] flex bg-black/65 md:items-center md:justify-center md:p-6" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) setOpen(false); }}><div role="dialog" aria-modal="true" aria-labelledby="delegate-title" className="flex h-full w-full flex-col overflow-hidden bg-canvas md:h-[min(780px,92vh)] md:max-w-5xl md:rounded-2xl md:border md:border-hairline/50">
    <header className="flex shrink-0 items-center gap-3 border-b border-hairline/50 px-4 py-3 sm:px-6"><div className="flex size-9 items-center justify-center rounded-xl bg-accent/15 text-accent"><Send size={17} /></div><div className="min-w-0 flex-1"><h2 id="delegate-title" className="text-[16px] font-semibold text-ink">Delegate work</h2><p className="truncate text-[11.5px] text-ink-secondary">Assignments run independently with unattended governance.</p></div><button aria-label="Close delegation" disabled={busy} onClick={() => setOpen(false)} className="flex size-9 items-center justify-center rounded-lg text-ink-secondary hover:bg-raised"><X size={19} /></button></header>
    <div className="grid min-h-0 flex-1 grid-cols-1 overflow-y-auto md:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)] md:overflow-hidden">
      <section className="border-b border-hairline/50 p-4 sm:p-6 md:overflow-y-auto md:border-b-0 md:border-r"><h3 className="text-[14px] font-semibold text-ink">New assignment</h3><div className="mt-4 grid gap-3">
        <label className="grid gap-1.5 text-[11.5px] text-ink-secondary">Delegated by<select value={sourceBotId} onChange={(event) => { setSourceBotId(event.target.value); if (event.target.value === targetBotId) setTargetBotId(""); }} className="min-h-11 rounded-xl border border-hairline/50 bg-card px-3 text-[13px] text-ink outline-none focus:border-accent"><option value="">You</option>{bots.map((bot) => <option key={bot.id} value={bot.id}>{bot.name} · {bot.title}</option>)}</select></label>
        <label className="grid gap-1.5 text-[11.5px] text-ink-secondary">Assign to<select value={targetBotId} onChange={(event) => setTargetBotId(event.target.value)} className="min-h-11 rounded-xl border border-hairline/50 bg-card px-3 text-[13px] text-ink outline-none focus:border-accent"><option value="">Choose an agent</option>{availableTargets.map((bot) => <option key={bot.id} value={bot.id}>{bot.name} · {bot.title}</option>)}</select></label>
        <label className="grid gap-1.5 text-[11.5px] text-ink-secondary">Assignment<textarea value={task} onChange={(event) => setTask(event.target.value)} maxLength={4000} rows={4} placeholder="Define the outcome, not just an activity…" className="resize-y rounded-xl border border-hairline/50 bg-card px-3 py-2.5 text-[13px] leading-5 text-ink outline-none focus:border-accent" /></label>
        <label className="grid gap-1.5 text-[11.5px] text-ink-secondary">Bounded handoff context <span className="text-[10px] text-ink-tertiary">Only include what this assignment needs.</span><textarea value={context} onChange={(event) => setContext(event.target.value)} maxLength={6000} rows={3} placeholder="Verified facts, constraints, links, or decisions…" className="resize-y rounded-xl border border-hairline/50 bg-card px-3 py-2.5 text-[13px] leading-5 text-ink outline-none focus:border-accent" /></label>
        <label className="grid gap-1.5 text-[11.5px] text-ink-secondary">Expected output<input value={expectedOutput} onChange={(event) => setExpectedOutput(event.target.value)} maxLength={1000} placeholder="For example: one-page decision memo" className="min-h-11 rounded-xl border border-hairline/50 bg-card px-3 text-[13px] text-ink outline-none focus:border-accent" /></label>
        {error && <div role="alert" className="rounded-lg bg-danger/10 px-3 py-2 text-[12px] text-danger">{error}</div>}
        <button onClick={() => void delegate()} disabled={busy || !targetBotId || !task.trim()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-4 text-[13px] font-medium text-white disabled:opacity-45">{busy ? <Loader2 size={15} className="animate-spin" /> : <Send size={15} />}{busy ? "Agent is working…" : "Delegate assignment"}</button><p className="text-[10.5px] leading-4 text-ink-tertiary">The result is saved as a closed task on the receiving agent. Sensitive actions pause in Today for approval.</p>
      </div></section>
      <section className="min-h-[360px] p-4 sm:p-6 md:overflow-y-auto"><div className="flex items-center justify-between"><div><h3 className="text-[14px] font-semibold text-ink">Delegation ledger</h3><p className="mt-0.5 text-[11.5px] text-ink-secondary">Durable ownership, outcomes, and failures.</p></div><span className="text-[11px] text-ink-secondary">{items.length}</span></div><div className="mt-4 space-y-3">{items.length === 0 && <div className="rounded-xl bg-inset px-4 py-8 text-center text-[13px] text-ink-secondary">No delegated assignments yet.</div>}{items.map((item) => <article key={item.id} className="rounded-xl border border-hairline/40 bg-card p-3.5"><div className="flex items-start gap-3"><span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-raised">{item.status === "completed" ? <CheckCircle2 size={16} className="text-success" /> : item.status === "failed" ? <XCircle size={16} className="text-danger" /> : <Clock3 size={16} className="text-warning" />}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5 text-[11px] text-ink-secondary"><span>{item.sourceBotName}</span><ArrowRight size={12} /><span className="font-medium text-ink">{item.targetBotName}</span><span>· {elapsed(item.updatedAt)}</span></div><h4 className="mt-1.5 text-[13px] font-medium leading-5 text-ink">{item.task}</h4>{item.status === "queued" && <p className="mt-2 text-[12px] leading-5 text-warning">Waiting for your approval before this agent starts.</p>}{item.result && <p className="mt-2 line-clamp-4 whitespace-pre-wrap text-[12px] leading-5 text-ink-secondary">{item.result}</p>}{item.error && <p className="mt-2 text-[12px] leading-5 text-danger">{item.error}</p>}<div className="mt-3 flex flex-wrap gap-2">{item.status === "queued" && <button disabled={retrying === item.id} onClick={() => void approve(item)} className="flex min-h-9 items-center gap-1.5 rounded-lg bg-success/15 px-3 text-[11.5px] font-medium text-success">{retrying === item.id ? <Loader2 size={13} className="animate-spin" /> : <Send size={13} />}Approve &amp; run</button>}{item.status === "completed" && item.targetThreadId && <button onClick={() => openResult(item)} className="flex min-h-9 items-center gap-1.5 rounded-lg bg-accent/10 px-3 text-[11.5px] font-medium text-accent"><BotIcon size={13} />Open agent task</button>}{item.status === "failed" && <button disabled={retrying === item.id} onClick={() => void retry(item)} className="flex min-h-9 items-center gap-1.5 rounded-lg bg-raised px-3 text-[11.5px] text-ink">{retrying === item.id ? <Loader2 size={13} className="animate-spin" /> : <RotateCcw size={13} />}Retry</button>}</div></div></div></article>)}</div></section>
    </div>
  </div></div>, document.body)}</>;
}
