import { useEffect, useState } from "react";
import { BookMarked, Check, ExternalLink, FileInput, Loader2, Plus, Save, Tag, X } from "lucide-react";
import { api } from "@/state/store";
import { cn } from "@/lib/cn";

type Capture = { id: string; title: string; sourceUrl: string | null; sourceType: string; content: string; tags: string[]; status: "pending" | "approved" | "corrected"; contextItemIds: string[]; reviewedAt: number | null; createdAt: number; updatedAt: number };
const tagList = (value: string) => [...new Set(value.split(",").map((item) => item.trim().toLowerCase()).filter(Boolean))];

export function KnowledgeCaptureDialog() {
  const [open, setOpen] = useState(false); const [captures, setCaptures] = useState<Capture[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [creating, setCreating] = useState(true);
  const [title, setTitle] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [content, setContent] = useState(""); const [tags, setTags] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const selected = captures.find((item) => item.id === selectedId) ?? null;
  const load = async (keepId?: string | null) => { const result = await api("/api/captures", { cache: "no-store" }) as { captures: Capture[] }; setCaptures(result.captures); if (keepId && result.captures.some((item) => item.id === keepId)) { setSelectedId(keepId); setCreating(false); } };
  useEffect(() => { if (!open) return; setBusy("load"); void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load captures")).finally(() => setBusy("")); }, [open]);
  useEffect(() => { if (!selected || creating) return; setTitle(selected.title); setSourceUrl(selected.sourceUrl ?? ""); setContent(selected.content); setTags(selected.tags.join(", ")); }, [selected, creating]);
  const startNew = () => { setCreating(true); setSelectedId(null); setTitle(""); setSourceUrl(""); setContent(""); setTags(""); setError(""); };
  const create = async () => { setBusy("create"); setError(""); try { const result = await api("/api/captures", { method: "POST", body: JSON.stringify({ title, sourceUrl, content, tags: tagList(tags) }) }) as { capture: Capture }; await load(result.capture.id); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not capture this knowledge"); } finally { setBusy(""); } };
  const review = async (action: "approve" | "correct" | "dismiss") => { if (!selectedId) return; setBusy(action); setError(""); try { await api(`/api/captures/${selectedId}`, { method: "PATCH", body: JSON.stringify({ action, title, content, tags: tagList(tags) }) }); await load(null); if (action !== "dismiss") setSelectedId(selectedId); else startNew(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not review this capture"); } finally { setBusy(""); } };
  const pending = captures.filter((item) => item.status === "pending").length; const canCreate = Boolean(content.trim() || sourceUrl.trim());

  return <>
    <button onClick={() => setOpen(true)} className="flex min-h-10 items-center gap-2 rounded-xl border border-hairline/40 bg-card px-3.5 text-[12.5px] font-medium text-ink hover:bg-inset"><FileInput size={15} className="text-accent" />Capture{pending > 0 && <span className="rounded-full bg-accent px-1.5 py-0.5 text-[9px] text-white">{pending}</span>}</button>
    {open && <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/55 p-0 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby="capture-title"><div className="flex max-h-[96dvh] w-full max-w-6xl flex-col overflow-hidden rounded-t-2xl border border-hairline/40 bg-card shadow-2xl sm:max-h-[90dvh] sm:rounded-2xl">
      <header className="flex items-start justify-between gap-4 border-b border-hairline/30 px-4 py-4 sm:px-5"><div><div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-[.14em] text-accent"><BookMarked size={14} />Ingest</div><h2 id="capture-title" className="mt-1 text-[20px] font-semibold text-ink">Capture useful knowledge</h2><p className="mt-1 text-[12px] text-ink-secondary">Nothing enters trusted context until you approve it.</p></div><button aria-label="Close capture inbox" onClick={() => setOpen(false)} className="flex size-10 shrink-0 items-center justify-center rounded-xl text-ink-secondary hover:bg-inset"><X size={18} /></button></header>
      <div className="grid min-h-0 flex-1 overflow-hidden md:grid-cols-[280px_minmax(0,1fr)]">
        <aside className="max-h-52 overflow-y-auto border-b border-hairline/30 p-3 md:max-h-none md:border-b-0 md:border-r"><button onClick={startNew} className="flex min-h-10 w-full items-center justify-center gap-2 rounded-xl bg-accent px-3 text-[12.5px] font-medium text-white"><Plus size={14} />New capture</button>{busy === "load" ? <div className="flex justify-center py-8"><Loader2 size={18} className="animate-spin text-accent" /></div> : <div className="mt-2 space-y-1">{captures.length === 0 && <div className="px-2 py-6 text-center text-[12px] text-ink-secondary">Your capture inbox is empty.</div>}{captures.map((item) => <button key={item.id} onClick={() => { setCreating(false); setSelectedId(item.id); setError(""); }} className={cn("w-full rounded-xl px-3 py-2.5 text-left", !creating && selectedId === item.id ? "bg-raised" : "hover:bg-inset")}><div className="line-clamp-2 text-[12.5px] font-medium text-ink">{item.title}</div><div className="mt-1 flex items-center gap-2 text-[10.5px] text-ink-secondary"><span className={cn("size-1.5 rounded-full", item.status === "pending" ? "bg-warning" : "bg-success")} />{item.status}{item.contextItemIds.length ? ` · ${item.contextItemIds.length} chunks` : ""}</div></button>)}</div>}</aside>
        <main className="min-h-0 overflow-y-auto p-4 sm:p-5">{error && <div role="alert" className="mb-4 rounded-xl bg-danger/10 px-3 py-2.5 text-[12.5px] text-danger">{error}</div>}<div className="space-y-4">
          <div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Title</span><input value={title} readOnly={Boolean(selected && selected.status !== "pending")} onChange={(event) => setTitle(event.target.value)} placeholder="What is this about?" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none read-only:opacity-70" /></label><label><span className="mb-1.5 block text-[12px] font-medium text-ink">Public source link</span><input type="url" value={sourceUrl} readOnly={Boolean(selected)} onChange={(event) => setSourceUrl(event.target.value)} placeholder="https://…" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none read-only:opacity-70" /></label></div>
          <label className="block"><span className="mb-1.5 flex items-center gap-1.5 text-[12px] font-medium text-ink"><Tag size={13} />Tags</span><input value={tags} readOnly={Boolean(selected && selected.status !== "pending")} onChange={(event) => setTags(event.target.value)} placeholder="research, customer, product" className="min-h-11 w-full rounded-xl border border-hairline/40 bg-inset px-3 text-[13px] text-ink focus:border-accent focus:outline-none read-only:opacity-70" /></label>
          <label className="block"><span className="mb-1.5 block text-[12px] font-medium text-ink">Knowledge</span>{creating && sourceUrl && !content && <span className="mb-2 block text-[11px] text-ink-secondary">Leave this empty to fetch readable text from the public link.</span>}<textarea value={content} readOnly={Boolean(selected && selected.status !== "pending")} onChange={(event) => setContent(event.target.value)} placeholder="Paste the useful answer, notes, research, or source text…" className="min-h-72 w-full resize-y rounded-xl border border-hairline/40 bg-inset p-3 text-[13px] leading-relaxed text-ink focus:border-accent focus:outline-none read-only:opacity-70" /></label>
          {selected?.sourceUrl && <a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-xl text-[12px] text-accent"><ExternalLink size={13} />Open original source</a>}
        </div></main>
      </div>
      <footer className="flex flex-col-reverse gap-2 border-t border-hairline/30 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div>{selected?.status === "pending" && <button disabled={Boolean(busy)} onClick={() => void review("dismiss")} className="min-h-10 rounded-xl px-3 text-[12px] text-ink-secondary hover:bg-danger/10 hover:text-danger">Dismiss</button>}</div><div className="flex flex-col-reverse gap-2 sm:flex-row">{creating ? <button disabled={!canCreate || Boolean(busy)} onClick={() => void create()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-5 text-[12.5px] font-medium text-white disabled:opacity-40">{busy === "create" ? <Loader2 size={14} className="animate-spin" /> : <Save size={14} />}Save to inbox</button> : selected?.status === "pending" ? <><button disabled={!content.trim() || Boolean(busy)} onClick={() => void review("correct")} className="flex min-h-11 items-center justify-center gap-2 rounded-xl border border-hairline/40 px-4 text-[12.5px] font-medium text-ink disabled:opacity-40">Save correction</button><button disabled={!content.trim() || Boolean(busy)} onClick={() => void review("approve")} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-accent px-5 text-[12.5px] font-medium text-white disabled:opacity-40">{busy === "approve" ? <Loader2 size={14} className="animate-spin" /> : <Check size={14} />}Approve knowledge</button></> : <span className="flex min-h-11 items-center gap-2 px-2 text-[12px] text-success"><Check size={14} />Trusted context</span>}</div></footer>
    </div></div>}
  </>;
}
