import { useEffect, useRef, useState } from 'react';
import { Megaphone, X } from 'lucide-react';
type Row = Record<string, unknown>;
const id=(row:Row)=>String(row.id??row._id??'');
const control='mt-2 w-full rounded-xl border border-hairline/50 bg-inset px-3 py-3 text-sm outline-none focus:border-accent';
const button='rounded-xl bg-control px-4 py-2.5 text-sm disabled:opacity-50';
const primary='rounded-xl bg-accent px-4 py-2.5 text-sm text-white disabled:opacity-50';
export function WhatsappCampaignList({campaigns,audiences,templates,creating,onCreating,request,onSaved}:{campaigns:Row[];audiences:Row[];templates:Row[];creating:boolean;onCreating:(value:boolean)=>void;request:(path:string,method?:string,body?:Row)=>Promise<any>;onSaved:(row:Row)=>void}) {
 const [filter,setFilter]=useState('All');const [name,setName]=useState('');const [description,setDescription]=useState('');const [audience,setAudience]=useState('');const [template,setTemplate]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [savedId,setSavedId]=useState('');
 const [openedId,setOpenedId]=useState('');
 const opened=campaigns.find(c=>id(c)===openedId);
 const readOnly=Boolean(opened && String(opened.status??'draft').toLowerCase()!=='draft');
 const dialog=useRef<HTMLDialogElement>(null);
 const close=()=>{setOpenedId('');onCreating(false);};
 useEffect(()=>{if(creating){setName('');setDescription('');setAudience('');setTemplate('');setSavedId('');setError('');}},[creating]);
 useEffect(()=>{if(creating||openedId)dialog.current?.showModal();else dialog.current?.close();},[creating,openedId]);
 const openCampaign=(c:Row)=>{setName(String(c.name??''));setDescription(String(c.description??''));setAudience(String(c.audience_id??''));setTemplate(String(c.template_id??''));setSavedId('');setError('');setOpenedId(id(c));};
 const approved=templates.filter(t=>String(t.meta_status??t.status).toLowerCase()==='approved');const chosen=approved.find(t=>id(t)===template);
 const visible=campaigns.filter(c=>filter==='All'||String(c.status).toLowerCase()===filter.toLowerCase());
 const save=async(start:boolean)=>{if(busy||readOnly)return;setBusy(true);setError('');try{
  if(!name.trim()||!audience||!chosen)throw new Error('Enter a name and choose an audience and approved template.');
  const payload={name:name.trim(),description:description.trim(),audience_id:audience,template_id:template,status:'draft',template_name:chosen.normalized_name??chosen.name,template_language:chosen.language};
  let campaignId=openedId||savedId;
  if(openedId){const result=await request(`whatsapp/campaigns/${openedId}`,'PATCH',payload);onSaved({...opened,...payload,...result,id:openedId});}
  if(!campaignId){const result=await request('whatsapp/campaigns','POST',payload);campaignId=id(result);if(!campaignId)throw new Error('Campaign created without an ID. Check the campaign list before retrying.');setSavedId(campaignId);onSaved({...payload,...result});}
  if(start){await request(`whatsapp/campaigns/${campaignId}/start`,'POST',{template_id:template});onSaved({...payload,id:campaignId,status:'active'});}
  close();
 }catch(e){setError(e instanceof Error?e.message:'Could not save campaign.');}finally{setBusy(false);}};
 return <div className="space-y-5"><div className="flex flex-wrap gap-2">{['All','Draft','Active','Paused','Completed','Failed'].map(f=><button key={f} className={f===filter?primary:button} aria-pressed={f===filter} onClick={()=>setFilter(f)}>{f}</button>)}</div>
 {!visible.length?<div className="flex min-h-72 flex-col items-center justify-center rounded-xl border border-dashed border-hairline/50 p-6 text-center"><Megaphone className="mb-4 text-ink-secondary" size={28}/><p className="font-medium">No campaigns in this view yet</p><p className="mt-2 text-sm text-ink-secondary">Create a campaign to start sending WhatsApp messages.</p><button className={primary+' mt-5'} onClick={()=>onCreating(true)}>+ New Campaign</button></div>:<div className="grid gap-3 sm:grid-cols-2">{visible.map(c=><button type="button" key={id(c)} onClick={()=>openCampaign(c)} className="rounded-xl border border-hairline/40 bg-card p-5 text-left hover:bg-control"><h3 className="font-medium">{String(c.name)}</h3><p className="mt-2 text-sm capitalize text-ink-secondary">{String(c.status??'draft')}</p></button>)}</div>}
 {!creating&&!openedId&&error&&<p role="alert" className="text-sm text-danger">{error}</p>}
 <dialog ref={dialog} aria-labelledby="new-wa-campaign" onCancel={e=>{if(busy)e.preventDefault();else close();}} className="fixed inset-0 m-auto max-h-[85vh] w-[calc(100%_-_2rem)] max-w-5xl overflow-y-auto rounded-2xl border border-hairline/50 bg-panel p-0 text-ink backdrop:bg-black/60"><header className="flex justify-between border-b border-hairline/40 p-6"><div><h3 id="new-wa-campaign" className="text-xl font-semibold">{openedId?'Campaign Details':'New Campaign'}</h3><p className="mt-2 text-sm text-ink-secondary">{openedId?'Review your WhatsApp campaign details and message preview':'Create a new WhatsApp campaign to reach your audience'}</p></div><button disabled={busy} aria-label="Close campaign" onClick={close}><X size={20}/></button></header>
 <div className="grid gap-6 p-6 md:grid-cols-2"><fieldset disabled={busy||Boolean(savedId)||readOnly} className="space-y-5"><h4 className="font-semibold">Campaign Details</h4><label className="block text-sm">Campaign Name *<input autoFocus className={control} value={name} onChange={e=>setName(e.target.value)} placeholder="Example: January Development Update"/></label><label className="block text-sm">Description (Optional)<input className={control} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Brief description"/></label><label className="block text-sm">Audience *<select className={control} value={audience} onChange={e=>setAudience(e.target.value)}><option value="">Select an audience</option>{audiences.map(a=><option key={id(a)} value={id(a)}>{String(a.name)}</option>)}</select></label><label className="block text-sm">Message Template *<select className={control} value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Select a template</option>{approved.map(t=><option key={id(t)} value={id(t)}>{String(t.name)}</option>)}</select></label></fieldset><aside className="flex min-h-80 items-center justify-center rounded-2xl bg-[#282d2b] p-6">{chosen?<div className="w-full rounded-xl bg-[#123d32] p-5 text-white"><p className="mb-3 text-xs text-white/60">{String(chosen.name)}</p><p className="whitespace-pre-wrap break-words text-sm">{String(chosen.body??'')}</p>{Boolean(chosen.footer_text)&&<p className="mt-3 text-xs text-white/60">{String(chosen.footer_text)}</p>}</div>:<p className="text-center text-sm text-white/60">Select a template to view preview here</p>}</aside></div>
 <footer className="border-t border-hairline/40 p-5">{error&&<p role="alert" className="mb-3 text-sm text-danger">{error}</p>}<div className="flex flex-wrap justify-end gap-3"><button disabled={busy} className={button} onClick={close}>Cancel</button><button disabled={readOnly||busy||!name.trim()||!audience||!template} className={button} onClick={()=>save(false)}>Save as Draft</button><button disabled={readOnly||busy||!name.trim()||!audience||!template} className={primary} onClick={()=>save(true)}>{busy?'Saving…':'Start Campaign'}</button></div></footer></dialog></div>;
}
