import { createPortal } from "react-dom";
import { api as localApi } from "@/state/store";
import { z } from "zod";
import { useEffect, useRef, useState } from 'react';
import { FileText, Plus, MoreHorizontal, Trash2, X } from 'lucide-react';
type Row = Record<string, any>;
type Button = { type: string; text: string; url?: string; phone_number?: string };
type Card = { bodyText: string; headerHandle: string; preview: string; buttons: Button[] };
const input = 'mt-2 w-full rounded-xl border border-hairline/50 bg-inset px-3 py-3 text-sm outline-none focus:border-accent';
const button = 'rounded-xl bg-control px-4 py-2.5 text-sm hover:brightness-110 disabled:opacity-50';
const primary = 'rounded-xl bg-accent px-4 py-2.5 text-sm text-white hover:brightness-110 disabled:opacity-50';
const tokens = (text: string) => [...new Set([...text.matchAll(/{{\s*([a-z_][a-z0-9_]*)\s*}}/g)].map(m => m[1]))];
export function WhatsappTemplates({ templates, request, refresh, actionTarget, onUpdate, onDelete }: { onUpdate: (row: Row) => void; onDelete: (id: string) => void; actionTarget?: HTMLDivElement | null; templates: Row[]; request: (path: string, method: string, body?: Row) => Promise<unknown>; refresh: () => Promise<void> }) {
 const [editing,setEditing]=useState<Row|null>(null);
 const [menu,setMenu]=useState<string|null>(null);
 const [deleting,setDeleting]=useState<Row|null>(null);
 const [purpose,setPurpose]=useState('');
 const [callPermission,setCallPermission]=useState(false);
 const [filter,setFilter]=useState('Approved');
 const [open,setOpen]=useState(false);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const [mode,setMode]=useState('Standard');
 const [name,setName]=useState('');
 const [category,setCategory]=useState('UTILITY');
 const [language,setLanguage]=useState('en_US');
 const [body,setBody]=useState('');
 const [header,setHeader]=useState(false);
 const [headerType,setHeaderType]=useState('TEXT');
 const [headerText,setHeaderText]=useState('');
 const [headerHandle,setHeaderHandle]=useState('');
 const [headerPreview,setHeaderPreview]=useState('');
 const [footer,setFooter]=useState(false);
 const [footerText,setFooterText]=useState('');
 const [buttonsEnabled,setButtonsEnabled]=useState(false);
 const [buttons,setButtons]=useState<Button[]>([]);
 const [cards,setCards]=useState<Card[]>([]);
 const [samples,setSamples]=useState<Record<string,string>>({});
 const [preview,setPreview]=useState(true);
 const [view,setView]=useState<Row|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const details=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 useEffect(()=>{if(view)details.current?.showModal();else details.current?.close();},[view]);
 const act=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Request failed.');}finally{setBusy(false);}};
 const api=async(path:string,payload:Row)=>{const result=await request('whatsapp/templates/'+path,'POST',payload) as Row;if(result?.success===false||result?.error)throw new Error(String(result.message??result.error));return result;};
 const upload=async(file:File,done:(handle:string,preview:string)=>void)=>{await act(async()=>{if(!file.type.startsWith('image/')||file.size>5*1024*1024)throw new Error('Choose an image smaller than 5 MB.');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('upload-image',{fileName:file.name,mimeType:file.type,fileBase64:data.split(',')[1]});if(!result.handle)throw new Error('Image upload returned no handle.');done(result.handle,data);});};
 const allTokens=tokens([body,mode==='Standard'&&header?headerText:'',...(mode==='Carousel'?cards.map(c=>c.bodyText):[]),...(mode==='Standard'&&buttonsEnabled?buttons.map(b=>b.url??''):[])].join(' '));
 const previewText=(text:string)=>text.replace(/{{\s*([^{}]+?)\s*}}/g,(_,key:string)=>samples[key]||`{{${key}}}`);
 const textComponent=(type:string,text:string)=>({type,text,...(type==='HEADER'?{format:'TEXT'}:{}),...(tokens(text).length?{example:{[type==='BODY'?'body_text_named_params':'header_text_named_params']:tokens(text).map(param_name=>({param_name,example:samples[param_name]}))}}:{})});
 const submit=()=>act(async()=>{
  if(!name.trim()||!body.trim())throw new Error('Enter a template name and message body.');
  if(/{{\s*\d+\s*}}/.test(body))throw new Error('Use named parameters such as {{name}}.');
  if(allTokens.some(t=>!samples[t]?.trim()))throw new Error('Provide an example for each parameter.');
  if(mode==='Carousel'&&(cards.length<2||cards.some(c=>!c.headerHandle||!c.bodyText.trim()||!c.buttons.length)))throw new Error('Add at least two cards, each with an image, body and button.');
  if(mode==='Standard'&&header&&headerType==='IMAGE'&&!headerHandle)throw new Error('Upload a header image.');
  const activeButtons=mode==='Standard'&&buttonsEnabled?buttons:[];
  if([...activeButtons,...(mode==='Carousel'?cards.flatMap(c=>c.buttons):[])].some(b=>!b.text.trim()||(b.type==='URL'&&!b.url?.startsWith('https://'))||(b.type==='PHONE_NUMBER'&&!b.phone_number?.trim())))throw new Error('Complete every button label and destination.');
  const components:Row[]=[];
  if(mode==='Standard'&&header)components.push(headerType==='TEXT'?textComponent('HEADER',headerText):{type:'HEADER',format:'IMAGE',example:{header_handle:[headerHandle]}});
  components.push(textComponent('BODY',body));
  if(mode==='Standard'&&footer&&footerText.trim())components.push({type:'FOOTER',text:footerText});
  if(mode==='Standard'&&callPermission)components.push({type:'CALL_PERMISSION_REQUEST'});
  if(activeButtons.length&&!callPermission)components.push({type:'BUTTONS',buttons:activeButtons});
  if(mode==='Carousel')components.push({type:'CAROUSEL',cards:cards.map(c=>({components:[{type:'HEADER',format:'IMAGE',example:{header_handle:[c.headerHandle]}},textComponent('BODY',c.bodyText),{type:'BUTTONS',buttons:c.buttons}]}))});
  await api(editing?'edit':'create',{...(editing?{templateId:String(editing.id??editing._id)}:{}),name:name.trim().toLowerCase().replace(/[^a-z0-9_]+/g,'_'),language,category:mode==='Carousel'?'MARKETING':category,...((mode==='Standard'||editing)?{components}:{}),...(mode==='Carousel'?{mainBody:body,cards:cards.map(({preview:_,...c})=>c)}:{headerHandle})});
  if(editing) onUpdate({...editing,body,header_enabled:header,header_type:headerType,header_text:headerText,footer_enabled:footer,footer_text:footerText,buttons_enabled:buttonsEnabled,buttons,carousel_cards:cards,meta_status:'PENDING'});
  else await refresh();
  setOpen(false);setFilter('Pending');
 });
 const editButtons=(items:Button[],change:(items:Button[])=>void,max=3)=><div className="space-y-3">{items.map((b,i)=><div key={i} className="rounded-xl border border-hairline/40 p-3"><div className="flex gap-2"><select aria-label="Button type" className={input} value={b.type} onChange={e=>change(items.map((v,j)=>j===i?{type:e.target.value,text:v.text}:v))}><option value="QUICK_REPLY">Quick reply</option><option value="URL">Website</option><option value="PHONE_NUMBER">Phone number</option></select><button type="button" aria-label="Remove button" onClick={()=>change(items.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><input aria-label="Button label" maxLength={25} className={input} placeholder="Button label" value={b.text} onChange={e=>change(items.map((v,j)=>j===i?{...v,text:e.target.value}:v))}/>{b.type!=='QUICK_REPLY'&&<input aria-label="Button destination" className={input} placeholder={b.type==='URL'?'https://example.com':'+15551234567'} value={b.url??b.phone_number??''} onChange={e=>change(items.map((v,j)=>j===i?{...v,[b.type==='URL'?'url':'phone_number']:e.target.value}:v))}/>}</div>)}<button type="button" className={button} disabled={items.length>=max} onClick={()=>change([...items,{type:'QUICK_REPLY',text:''}])}>+ Add button</button></div>;
 const editTemplate=(row:Row)=>{
  const array=(value:any)=>{try{return typeof value==='string'?JSON.parse(value):value??[];}catch{return [];}};
  setEditing(row);setMenu(null);setError('');setMode(row.template_type==='carousel'?'Carousel':'Standard');setName(String(row.name??''));setBody(String(row.body??''));setCategory(String(row.category??'UTILITY').toUpperCase());setLanguage(String(row.language??'en_US'));
  setHeader(Boolean(row.header_enabled));setHeaderType(String(row.header_type??'TEXT').toUpperCase());setHeaderText(String(row.header_text??''));setHeaderHandle('');setHeaderPreview('');setFooter(Boolean(row.footer_enabled));setFooterText(String(row.footer_text??''));setButtonsEnabled(Boolean(row.buttons_enabled));setButtons(array(row.buttons).map((b:Button)=>({...b,type:b.type.toUpperCase()})));setCards(array(row.carousel_cards).map((c:Row)=>({bodyText:c.bodyText??c.body_text??'',headerHandle:c.headerHandle??'',preview:'',buttons:array(c.buttons).map((b:Button)=>({...b,type:b.type.toUpperCase()}))})));setSamples({});setCallPermission(false);setOpen(true);
 };
 const group=(r:Row)=>String(r.meta_status??r.status??'PENDING').toUpperCase()==='APPROVED'?'Approved':['REJECTED','FAILED','DISABLED','PAUSED'].includes(String(r.meta_status??r.status).toUpperCase())?'Failed':'Pending';
 const filtered=templates.filter(r=>group(r)===filter);
 return <div className="space-y-5">
  {actionTarget && createPortal(<button className={primary+' ml-auto inline-flex items-center gap-2'} onClick={()=>{setEditing(null);setCallPermission(false);setName('');setBody('');setCards([]);setButtons([]);setHeader(false);setFooter(false);setButtonsEnabled(false);setSamples({});setHeaderHandle('');setHeaderPreview('');setHeaderText('');setFooterText('');setError('');setOpen(true);}}><Plus size={16}/>Create Template</button>,actionTarget)}
  <div className="flex flex-wrap items-center gap-2">{['Approved','Pending','Failed'].map(status=><button key={status} aria-pressed={filter===status} className={filter===status?primary:button} onClick={()=>setFilter(status)}>{status}</button>)}</div>
  {!filtered.length?<div className="flex min-h-64 flex-col items-center justify-center rounded-xl border border-dashed border-hairline/50 p-6 text-center"><FileText size={28} className="mb-4 text-ink-secondary"/><p className="font-medium">No {filter.toLowerCase()} templates yet</p><p className="mt-2 text-sm text-ink-secondary">Templates with this status will appear here.</p></div>:<div className="grid gap-3 sm:grid-cols-2">{filtered.map((row,i)=><div key={String(row.id??i)} className="relative flex min-h-28 min-w-0 items-center rounded-xl border border-hairline/40 bg-card"><button onClick={()=>{setMenu(null);setView(row);}} className="min-h-28 min-w-0 flex-1 rounded-xl p-5 text-left font-medium hover:bg-control">{String(row.name)}</button><div className="relative mr-3"><button disabled={busy} aria-label={`Actions for ${row.name}`} aria-expanded={menu===String(row.id)} className="rounded-lg p-2 hover:bg-control" onClick={()=>setMenu(menu===String(row.id)?null:String(row.id))}><MoreHorizontal size={20}/></button>{menu===String(row.id)&&<div className="absolute right-0 top-full z-20 min-w-32 rounded-lg border border-hairline/50 bg-panel p-1 shadow-xl" onKeyDown={e=>{if(e.key==='Escape')setMenu(null);}}><button className="block w-full rounded px-3 py-2 text-left text-sm hover:bg-control" onClick={()=>editTemplate(row)}>Edit</button><button className="block w-full rounded px-3 py-2 text-left text-sm text-danger hover:bg-control" onClick={()=>{setMenu(null);setError('');setDeleting(row);}}>Delete</button></div>}</div></div>)}</div>}
  {deleting&&<div className="rounded-xl border border-danger/40 p-4"><p className="text-sm">Delete “{String(deleting.name)}” from WhatsApp? This cannot be undone.</p><div className="mt-3 flex gap-2"><button disabled={busy} className={button+' text-danger'} onClick={()=>act(async()=>{await api('delete',{templateId:String(deleting.id??deleting._id)});onDelete(String(deleting.id??deleting._id));setDeleting(null);})}>Delete template</button><button disabled={busy} className={button} onClick={()=>setDeleting(null)}>Cancel</button></div></div>}
  {error&&!open&&<p role="alert" className="text-sm text-danger">{error}</p>}
  <dialog ref={details} aria-labelledby="wa-details-title" onCancel={()=>setView(null)} className="fixed inset-0 m-auto h-[82vh] max-h-[900px] w-[calc(100%_-_2rem)] max-w-4xl overflow-hidden rounded-2xl border border-hairline/50 bg-panel p-0 text-ink shadow-xl backdrop:bg-black/60">{view&&<div className="flex h-full flex-col">
    <header className="flex items-start justify-between border-b border-hairline/40 p-6"><div><h3 id="wa-details-title" className="text-xl font-semibold">Template Details</h3><p className="mt-2 text-sm text-ink-secondary">Review the template details and preview.</p></div><button autoFocus aria-label="Close template details" className="rounded-lg p-1 hover:bg-control" onClick={()=>setView(null)}><X size={20}/></button></header>
    <div className="min-h-0 flex-1 space-y-6 overflow-y-auto p-6">
      <label className="block text-sm font-medium">Template Name<input readOnly className={input} value={String(view.name??'')}/><span className="mt-2 block text-xs font-normal text-ink-secondary">Normalized: {String(view.normalized_name??view.name??'')}</span></label>
      <div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Category<input readOnly className={input+' capitalize'} value={String(view.category??'—')}/></label><label className="block text-sm font-medium">Language<input readOnly className={input} value={String(view.language??'—')}/></label></div>
      <label className="block text-sm font-medium">Message<textarea readOnly rows={8} className={input+' resize-none leading-relaxed'} value={String(view.body??'')}/><span className="mt-2 block text-xs font-normal text-ink-secondary">{String(view.body??'').length} characters</span></label>
      {Boolean(view.header_enabled)&&view.header_text&&<label className="block text-sm font-medium">Header<input readOnly className={input} value={String(view.header_text)}/></label>}
      {Boolean(view.footer_enabled)&&view.footer_text&&<label className="block text-sm font-medium">Footer<input readOnly className={input} value={String(view.footer_text)}/></label>}
      <div className="flex flex-wrap items-center gap-3 rounded-xl border border-hairline/50 bg-card/50 p-5"><span className="rounded-full border border-hairline/50 px-3 py-1.5 text-xs uppercase text-ink-secondary">{view.template_type==='carousel'?'Carousel':view.header_type||'Text'}</span><span className={'rounded-full border px-3 py-1.5 text-xs font-medium uppercase '+(group(view)==='Approved'?'border-emerald-500/30 bg-emerald-500/10 text-emerald-500':group(view)==='Failed'?'border-danger/30 text-danger':'border-hairline/50 text-ink-secondary')}>{String(view.meta_status??view.status??'Pending')}</span><span className="text-xs text-ink-secondary">{(()=>{const raw=view.created_at??view._creation_time;const date=new Date(typeof raw==='number'?raw:typeof raw==='string'&&/^\d+$/.test(raw)?Number(raw):String(raw));return Number.isNaN(date.getTime())?'Creation date unavailable':'Created '+date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});})()}</span></div>
    </div>
    <footer className="flex justify-end border-t border-hairline/40 p-5"><button className={button} onClick={()=>setView(null)}>Close</button></footer>
  </div>}</dialog>

  <dialog ref={dialog} aria-labelledby="wa-template-title" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}} className="fixed inset-0 m-auto h-[85vh] w-[calc(100%_-_2rem)] max-w-6xl overflow-hidden rounded-2xl border border-hairline/50 bg-panel p-0 text-ink shadow-xl backdrop:bg-black/65">
   <form className="flex h-full flex-col" onSubmit={e=>{e.preventDefault();void submit();}}>
    <header className="flex flex-wrap items-center gap-4 border-b border-hairline/40 p-5"><div className="mr-auto"><h3 id="wa-template-title" className="text-xl font-semibold">{editing?'Edit Template':'Create New Template'}</h3><p className="mt-1 text-sm text-ink-secondary">Design a WhatsApp message template</p></div><div className="flex rounded-full bg-control p-1">{['Standard','Carousel'].map(m=><button disabled={busy||Boolean(editing)} key={m} type="button" aria-pressed={mode===m} className={'rounded-full px-5 py-2 text-sm '+(mode===m?'bg-accent text-white':'')} onClick={()=>setMode(m)}>{m}</button>)}</div><button type="button" disabled={busy} aria-label="Close editor" onClick={()=>setOpen(false)}><X size={20}/></button></header>
    <div className={'grid min-h-0 flex-1 overflow-y-auto md:overflow-hidden '+(preview?'md:grid-cols-2':'')}>
     <fieldset disabled={busy} className="min-w-0 space-y-6 p-5 md:overflow-y-auto">{editing&&<p className="text-sm text-ink-secondary">Edit the message content below. Template name, language and category remain fixed. Upload a new image when editing an image header.</p>}
      <details className="rounded-xl border border-hairline/50 bg-card p-4"><summary className="cursor-pointer text-sm font-medium">Generate {mode==='Carousel'?'Carousel ':''}with AI</summary><textarea aria-label="Describe your template" className={input} value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Describe the message, audience and tone"/><button type="button" className={button+' mt-3'} disabled={!purpose.trim()||busy} onClick={()=>act(async()=>{
        const result=await localApi('/api/ai/generate-prompt',{method:'POST',body:JSON.stringify({prompt:`Write a WhatsApp ${mode} template in ${language}. Return only JSON with name, body, and cards (an array of 2 to 10 objects with bodyText, only for carousel). Use named {{name}} placeholders if needed. Do not invent URLs or phone numbers. Purpose: ${purpose}`})});
        const text=z.object({text:z.string()}).parse(result).text;
        const generated=z.object({name:z.string(),body:z.string(),cards:z.array(z.object({bodyText:z.string()})).min(2).max(10).optional()}).parse(JSON.parse(text.replace(/^```(?:json)?\s*|\s*```$/g,'')));
        if(mode==='Carousel'&&!generated.cards)throw new Error('AI did not return carousel cards. Try again.');
        setName(generated.name);setBody(generated.body);if(mode==='Carousel')setCards(generated.cards!.map(c=>({...c,headerHandle:'',preview:'',buttons:[]})));
      })}>Generate draft</button><p className="mt-2 text-xs text-ink-secondary">Uses your configured Analysis AI. Review the draft before creating the template.</p></details>
      <label className="block text-sm font-medium">Template Name *<input autoFocus required readOnly={Boolean(editing)} className={input} placeholder="e.g. order_confirmation" value={name} onChange={e=>setName(e.target.value)}/><span className="mt-2 block text-xs text-ink-secondary">Will be converted to: {name.toLowerCase().replace(/[^a-z0-9_]+/g,'_')||'lowercase_with_underscores'}</span></label>
      {mode==='Standard'&&<label className="block text-sm">Category<select disabled={Boolean(editing)} className={input} value={category} onChange={e=>setCategory(e.target.value)}><option value="UTILITY">Utility (Transactional)</option><option value="MARKETING">Marketing</option></select></label>}
      {mode==='Standard'&&<label className="flex gap-3 rounded-xl border border-hairline/50 p-4 text-sm"><input type="checkbox" checked={callPermission} onChange={e=>{setCallPermission(e.target.checked);if(e.target.checked){setCategory('UTILITY');setButtonsEnabled(false);}}}/>Create a call permission request template</label>}
      <label className="block text-sm">Language<select disabled={Boolean(editing)} className={input} value={language} onChange={e=>setLanguage(e.target.value)}>{['en_US','en_GB','hi','te','ta','es','fr','de','pt_BR','ar'].map(l=><option key={l}>{l}</option>)}</select></label>
      {mode==='Standard'&&<section className="border-t border-hairline/40 pt-5"><label className="flex justify-between text-sm">Header (Optional)<span><input type="checkbox" checked={header} onChange={e=>setHeader(e.target.checked)}/> Enable Header</span></label>{header&&<><select aria-label="Header type" className={input} value={headerType} onChange={e=>setHeaderType(e.target.value)}><option>TEXT</option><option>IMAGE</option></select>{headerType==='TEXT'?<input aria-label="Header text" maxLength={60} className={input} value={headerText} onChange={e=>setHeaderText(e.target.value)}/>:<input aria-label="Header image" className={input} type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,(h,p)=>{setHeaderHandle(h);setHeaderPreview(p);});}}/>}</>}</section>}
      <label className="block text-sm font-medium">{mode==='Carousel'?'Main Body Text':'Message Body'} *<textarea required rows={6} maxLength={1024} className={input} placeholder="Enter your message. Use {{name}}, {{phone_number}}, {{email}}" value={body} onChange={e=>setBody(e.target.value)}/></label>
      <div className="flex flex-wrap gap-2">{['name','phone_number','email'].map(t=><button key={t} type="button" className="rounded bg-control px-2 py-1 text-xs" onClick={()=>setBody(v=>v+` {{${t}}}`)}>{`{{${t}}}`}</button>)}</div>
      {mode==='Standard'?<><section className="border-t border-hairline/40 pt-5"><label className="flex justify-between text-sm">Footer (Optional)<span><input type="checkbox" checked={footer} onChange={e=>setFooter(e.target.checked)}/> Enable Footer</span></label>{footer&&<input aria-label="Footer text" maxLength={60} className={input} value={footerText} onChange={e=>setFooterText(e.target.value)}/>}</section><section className="space-y-3 border-t border-hairline/40 pt-5"><label className="flex justify-between text-sm">Buttons (Optional)<span><input type="checkbox" disabled={callPermission} checked={buttonsEnabled} onChange={e=>setButtonsEnabled(e.target.checked)}/> Enable Buttons</span></label>{buttonsEnabled&&editButtons(buttons,setButtons)}</section></>:<section className="space-y-4 border-t border-hairline/40 pt-5"><div className="flex items-center justify-between"><span>Cards ({cards.length}/10)</span><button type="button" className={primary} disabled={cards.length>=10} onClick={()=>setCards([...cards,{bodyText:'',headerHandle:'',preview:'',buttons:[]}])}>+ Add Card</button></div><p className="text-sm text-ink-secondary">{cards.length<2?'Add at least two cards.':'✓ Minimum two cards added'} Each card needs an image, message and button.</p>{cards.map((c,i)=><div key={i} className="space-y-3 rounded-xl border border-hairline/50 p-4"><div className="flex justify-between"><span>Card {i+1}</span><button type="button" aria-label={`Remove card ${i+1}`} onClick={()=>setCards(cards.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div><input aria-label={`Card ${i+1} image`} type="file" accept="image/*" className={input} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f,(h,p)=>setCards(old=>old.map((v,j)=>j===i?{...v,headerHandle:h,preview:p}:v)));}}/>{c.headerHandle&&<p className="text-xs text-ink-secondary">Image uploaded</p>}<textarea aria-label={`Card ${i+1} body`} className={input} value={c.bodyText} onChange={e=>setCards(cards.map((v,j)=>j===i?{...v,bodyText:e.target.value}:v))}/>{editButtons(c.buttons,b=>setCards(cards.map((v,j)=>j===i?{...v,buttons:b}:v)),2)}</div>)}</section>}
      {allTokens.length>0&&<section className="space-y-3"><h4 className="text-sm font-medium">Parameter examples for review</h4>{allTokens.map(t=><label key={t} className="block text-xs">{t}<input required className={input} value={samples[t]??''} onChange={e=>setSamples({...samples,[t]:e.target.value})}/></label>)}</section>}
      <p className="rounded-xl border border-hairline/50 bg-card p-4 text-sm leading-relaxed text-ink-secondary">Templates are submitted to Meta for approval. Use clear wording and examples for named parameters. Only approved templates can be used in campaigns.</p>
      {!preview&&<button type="button" className={button} onClick={()=>setPreview(true)}>Show preview</button>}
     </fieldset>
     {preview&&<aside className="min-w-0 p-5 md:overflow-auto md:border-l md:border-hairline/40"><div className="flex min-h-full flex-col rounded-2xl bg-[#282d2b] p-5"><div className="flex justify-between border-b border-white/10 pb-4 text-white"><h4 className="font-medium">WhatsApp Preview</h4><button type="button" className="text-sm text-white/60" onClick={()=>setPreview(false)}>Hide</button></div><div className="my-auto py-8"><div className="rounded-xl rounded-tl-none bg-[#123d32] p-4 text-sm text-white shadow-lg">{mode==='Standard'&&header&&(headerType==='IMAGE'&&headerPreview?<img src={headerPreview} alt="Header preview" className="mb-3 max-h-40 w-full rounded object-cover"/>:<p className="mb-2 font-semibold">{previewText(headerText)}</p>)}<p className="whitespace-pre-wrap break-words">{previewText(body)||'Your message will appear here…'}</p>{mode==='Standard'&&footer&&<p className="mt-3 text-xs text-white/60">{footerText}</p>}{mode==='Standard'&&buttonsEnabled&&buttons.map((b,i)=><div key={i} className="mt-3 border-t border-white/10 pt-2 text-center text-[#8ce4ca]">{b.text||'Button'}</div>)}</div>{mode==='Carousel'&&<div className="mt-3 flex gap-3 overflow-x-auto pb-3">{cards.length?cards.map((c,i)=><div key={i} className="w-52 shrink-0 rounded-xl bg-[#123d32] p-3 text-sm text-white">{c.preview&&<img src={c.preview} alt={`Card ${i+1}`} className="mb-3 h-28 w-full rounded object-cover"/>}<p className="whitespace-pre-wrap">{previewText(c.bodyText)||'Card message'}</p>{c.buttons.map((b,j)=><p key={j} className="mt-2 border-t border-white/10 pt-2 text-center text-[#8ce4ca]">{b.text||'Button'}</p>)}</div>):<p className="p-5 text-sm text-white/60">Add cards to view preview</p>}</div>}</div></div></aside>}
    </div>
    <footer className="border-t border-hairline/40 p-4">{error&&<p role="alert" className="mb-3 text-sm text-danger">{error}</p>}<div className="flex justify-end gap-3"><button disabled={busy} type="button" className={button} onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className={primary}>{busy?'Saving…':editing?'Save Changes':'Create Template'}</button></div></footer>
   </form>
  </dialog>
 </div>;
}
